export const CONFIG = {
  CLIFF_HEIGHT: 20,
  CLIFF_WIDTH: 8,
  CLIFF_DEPTH: 6,
  WATER_LEVEL: 0,
  POOL_WIDTH: 20,
  POOL_DEPTH: 20,

  GRAVITY: -25,
  MAX_JUMP_POWER: 18,
  MIN_JUMP_POWER: 6,
  POWER_CHARGE_RATE: 100,
  POWER_DECAY_RATE: 50,

  FLIP_SPEED: 4,
  TWIST_SPEED: 4,
  AIR_CONTROL: 0.5,

  CAMERA_OFFSET_Y: 3,
  CAMERA_OFFSET_Z: 8,
  CAMERA_FOLLOW_SPEED: 5,
  CAMERA_LOOK_AHEAD: 3,

  WATER_SPLASH_COUNT: 80,
  WATER_SPLASH_SPREAD: 3,
  WATER_SPLASH_HEIGHT: 5,

  PERFECT_VERTICAL_THRESHOLD: 0.1,
  GOOD_VERTICAL_THRESHOLD: 0.3,

  COLORS: {
    SKY: 0x87CEEB,
    CLIFF: 0x696969,
    WATER: 0x1E90FF,
    PLAYER: 0xFFD700,
    SKIN: 0xFDBF6F,
    SWIMSUIT: 0xFF6347
  }
};

export const GAME_STATE = {
  IDLE: 'idle',
  CHARGING: 'charging',
  JUMPING: 'jumping',
  FALLING: 'falling',
  ENTERED_WATER: 'entered_water',
  SCORED: 'scored'
};
